# Generated by Django 5.2.1 on 2025-05-31 08:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prompts',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Prompts', models.TextField()),
                ('check_in', models.DateTimeField()),
                ('check_out', models.DateTimeField()),
                ('uploadfiles', models.TextField()),
                ('users', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.users')),
            ],
        ),
    ]
